name: 'Pull Request'

on:
  pull_request:
    branches:
      - develop
      - main
      - master

  repository_dispatch:
    types:
      - contract-published
      - verification-results-published

env:
  PACT_BROKER_BASE_URL: https://playtomic-nacho.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.replaced }}

    steps:
      - uses: actions/checkout@v2
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
        shell: bash

      - name: Version
        uses: frabert/replace-string-action@v2.0
        id: versiongit rev-parse --abbrev-ref HEAD
        with:
          pattern: '/'
          string: "${{github.ref_name}}-${{steps.date.outputs.date}}-${{github.run_number}}-${{github.sha}}"
          flags: 'g'
          replace-with: '-'

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn -B clean compile -U --file pom.xml

      - name: Get PR source branch
        id: source-branch
        run: echo "::set-output name=source_branch::$(git rev-parse --abbrev-ref HEAD)"

      - name: Verify
        run: mvn -B verify -Dpact.provider.version=${{steps.version.outputs.replaced}} -Dpact.verifier.publishResults=true -Dpact.provider.branch=${{ steps.source-branch.outputs.source_branch }} --file pom.xml

      - run: docker pull pactfoundation/pact-cli:latest
        if: hashFiles('target/pacts') != ''

      - name: Publish pacts
        if: hashFiles('target/pacts') != ''
        run: docker run --rm -v ${PWD}:${PWD} -e PACT_BROKER_BASE_URL -e PACT_BROKER_TOKEN pactfoundation/pact-cli publish ${PWD}/target/pacts --consumer-app-version ${{steps.version.outputs.replaced}} --branch ${{ steps.source-branch.outputs.source_branch }}

      - name: Can I deploy?
        run: |
          docker run --rm -v ${PWD}:${PWD} -e PACT_BROKER_BASE_URL -e PACT_BROKER_TOKEN pactfoundation/pact-cli broker can-i-deploy \
          --pacticipant UsersService \
          --version ${{steps.version.outputs.replaced}} \
          --to-environment ${{ github.ref_name }} \
          --retry-while-unknown 0 \
          --retry-interval 10
